# Publish to PowerShell Gallery with this key
environment:
  NuGetApiKey:
    secure: VMvVbhuMaUTbI8WgnJH/WF7UBGwj261AgERGm25s21zQErHoIdwacoF3yd6OjIWh

os: WMF 5

# Skip on updates to the readme.
skip_commits:
  message: /updated readme.*/|update readme.*s/

build: false

test_script:
- ps: . .\build.ps1
